// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFV3PaylH4ZePBu7_ZtsbsZzbDAOVgRhI',
    appId: '1:28061750512:android:4af92f1621df3fb848de35',
    messagingSenderId: '28061750512',
    projectId: 'resilio-mental-health-app',
    authDomain: 'resilio-mental-health-app.firebaseapp.com',
    storageBucket: 'resilio-mental-health-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjT61JSTvqtKaYP7EbKG_Bv0Mk_Cbnnk',
    appId: '1:28061750512:ios:9c4e18b1c709b4ce48de35',
    messagingSenderId: '28061750512',
    projectId: 'resilio-mental-health-app',
    authDomain: 'resilio-mental-health-app.firebaseapp.com',
    storageBucket: 'resilio-mental-health-app.firebasestorage.app',
    androidClientId: '28061750512-f7tp46dl17irh1kdvb8qk8g78d6vu575.apps.googleusercontent.com',
    iosClientId: '28061750512-4hbgtg7n3v2tshiv0jbpdfkrjko68j7h.apps.googleusercontent.com',
    iosBundleId: 'com.islington.resilio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYjT61JSTvqtKaYP7EbKG_Bv0Mk_Cbnnk',
    appId: '1:28061750512:ios:9c4e18b1c709b4ce48de35',
    messagingSenderId: '28061750512',
    projectId: 'resilio-mental-health-app',
    authDomain: 'resilio-mental-health-app.firebaseapp.com',
    storageBucket: 'resilio-mental-health-app.firebasestorage.app',
    androidClientId: '28061750512-f7tp46dl17irh1kdvb8qk8g78d6vu575.apps.googleusercontent.com',
    iosClientId: '28061750512-4hbgtg7n3v2tshiv0jbpdfkrjko68j7h.apps.googleusercontent.com',
    iosBundleId: 'com.islington.resilio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEo8bl0pD2l6__utU5APFgWqFWEzWS7Ic',
    appId: '1:28061750512:web:8bdda4d59622b94448de35',
    messagingSenderId: '28061750512',
    projectId: 'resilio-mental-health-app',
    authDomain: 'resilio-mental-health-app.firebaseapp.com',
    storageBucket: 'resilio-mental-health-app.firebasestorage.app',
    measurementId: 'G-L0XQQQL561',
  );

}